[package]
name = "aoc2020-rs"
version = "0.1.0"
authors = ["ThePuzzlemaker <tpzker@thepuzzlemaker.info>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
humantime = "2.0.1"
ansi_term = "0.12.1"
itertools = "0.9.0"
rayon = "1.5.0"